development:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'mysql://root@localhost/lionmount'
    pool: 5
test:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'mysql://root@localhost/lionmount'
    pool: 5
production:
    adapter: mysql
    encoding: utf8
    reconnect: false
    database: 'mysql://root@localhost/lionmount'
    pool: 5
