development:
  adapter: postgresql
  encoding: utf8
  database: lionmount
  pool: 5
  username: lionmount
  password: lionmount123
test:
  adapter: postgresql
  encoding: utf8
  database: lionmount
  pool: 5
  username: lionmount
  password: lionmount123
production:
  adapter: postgresql
  encoding: utf8
  database: lionmount
  pool: 5
  username: lionmount
  password: lionmount123
