development:
  adapter: postgresql
  encoding: unicode
  database: lionmount
  pool: 5
  username: lionmount
  password: lionmount123
test:
  adapter: postgresql
  encoding: unicode
  database: lionmount
  pool: 5
  username: lionmount
  password: lionmount123
production:
    adapter: mysql2
    encoding: utf8
    reconnect: false
    database: 'lionmount'
    pool: 5
    username: rootsdf
    password:

